begin;
create extension if not exists pgtap with schema extensions;
select plan(8);
grant authenticated, masarifi_api, masarifi_worker, masarifi_migration to current_user with inherit true, set true;
set local role masarifi_migration;
insert into public.profiles(id,status) values('privacy_owner','active'),('privacy_admin','active');
insert into public.admin_profiles(user_id,status) values('privacy_admin','active');
insert into private.privacy_export_requests(user_id,status,scope,verified_at) values('privacy_owner','verified','["identity@1"]',clock_timestamp());
select throws_ok($$insert into private.privacy_export_requests(user_id,status) values('privacy_owner','requested')$$,'23505',null,'one active export per owner');
insert into private.account_deletion_requests(user_id,status,verified_at,cooling_off_ends_at) values('privacy_owner','verified',clock_timestamp(),clock_timestamp()+interval '24 hours');
select throws_ok($$insert into private.account_deletion_requests(user_id,status,cooling_off_ends_at) values('privacy_owner','requested',clock_timestamp()+interval '24 hours')$$,'23505',null,'one active deletion per owner');
insert into private.retention_policies(resource_type,retention_days,deletion_mode,legal_basis) values('identity-profile',365,'anonymize','Approved account privacy policy');
insert into private.retention_holds(resource_type,resource_id,reason,created_by) values('identity-profile','privacy_owner','Required legal preservation hold','privacy_admin');
select ok(exists(select 1 from private.retention_holds where resource_id='privacy_owner' and (ends_at is null or ends_at>clock_timestamp())),'active hold found by bounded key');
select throws_ok($$insert into private.retention_holds(resource_type,resource_id,reason,created_by) values('identity-profile','privacy_owner','Overlapping preservation attempt','privacy_admin')$$,'23505','RETENTION_HOLD_OVERLAP','overlapping hold rejected');
select throws_ok($$insert into private.retention_policies(resource_type,retention_days,deletion_mode,legal_basis) values('bad',-1,'delete','Approved legal basis')$$,'23514',null,'negative retention rejected');
select throws_ok($$insert into private.retention_policies(resource_type,retention_days,deletion_mode,legal_basis) values('bad-mode',1,'erase','Approved legal basis')$$,'23514',null,'unknown mode rejected');
select ok(not has_table_privilege('authenticated','private.privacy_export_requests','SELECT'),'authenticated cannot bypass privacy API');
select ok(not has_table_privilege('masarifi_worker','private.retention_holds','UPDATE'),'worker cannot alter holds');
select * from finish();
rollback;
