begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select has_index('public','abuse_reports','abuse_reports_active_uq','active abuse report dedupe is indexed');
grant masarifi_migration,masarifi_api to current_user with inherit true,set true;
grant usage on schema extensions to masarifi_api;
set local role masarifi_migration;
insert into public.profiles(id,status) values('phase11-feedback-owner','active'),('phase11-feedback-other','active');
reset role;
select set_config('request.jwt.claims','{"sub":"phase11-feedback-owner","role":"authenticated"}',true);
set local role masarifi_api;
select isnt(private.create_feedback('phase11-feedback-owner','idea',null,'Safe idea'),null::uuid,'feedback receipt is created');
select is(private.create_abuse_report('phase11-feedback-owner','other','resource-1','Reason'),private.create_abuse_report('phase11-feedback-owner','other','resource-1','Reason'),'active abuse replay deduplicates');
reset role;
select set_config('request.jwt.claims','{"sub":"phase11-feedback-other","role":"authenticated"}',true);
set local role masarifi_api;
select is((select count(*) from public.feedback_items),0::bigint,'other user cannot enumerate feedback');
select is((select count(*) from public.abuse_reports),0::bigint,'other user cannot enumerate reports');
reset role;
select * from finish();
rollback;
