import { createHash } from 'node:crypto';

export const CLIENT_PERMISSION_KEYS = Object.freeze([
  'admin.overview.read',
  'users.read',
  'imports.read',
  'imports.detail.read',
  'imports.failures.manage',
  'imports.confidence.manage',
  'imports.duplicates.manage',
  'imports.unsupported.manage',
  'parsers.coverage.read',
  'parsers.senders.manage',
  'parsers.rules.read',
  'parsers.rules.manage',
  'parsers.tests.run',
  'parsers.versions.manage',
  'parsers.merchants.manage',
  'parsers.categories.manage',
  'system-health.read',
  'system-health.api.read',
  'system-health.database.read',
  'system-health.storage.read',
  'system-health.providers.read',
  'jobs.queues.read',
  'jobs.runs.read',
  'jobs.runs.retry',
  'jobs.runs.cancel',
  'jobs.schedules.read',
  'global-search.use',
  'attention.read',
  'admin-team.read',
  'admin-team.invite',
  'admin-team.disable',
  'admin-team.sessions.revoke',
  'admin-team.roles.assign',
  'roles.read',
  'roles.manage',
  'permissions.read',
  'permissions.manage',
  'settings.general.read',
  'settings.general.manage',
  'settings.mobile.read',
  'settings.mobile.manage',
  'settings.flags.read',
  'settings.flags.manage',
  'settings.imports.read',
  'settings.imports.manage',
  'settings.ai.read',
  'settings.ai.manage',
  'settings.subscriptions.read',
  'settings.subscriptions.manage',
  'settings.security.read',
  'settings.security.manage',
  'settings.maintenance.read',
  'settings.maintenance.manage',
  'devices.read',
  'sessions.read',
  'users.status.manage',
  'users.verification.manage',
  'devices.revoke',
  'sessions.revoke',
  'users.export_summary',
  'support.request_access',
  'support.access.read',
  'support.access.approve',
  'support.access.revoke',
  'support.access.use',
  'subscriptions.read',
  'subscriptions.detail.read',
  'subscriptions.manage',
  'plans.read',
  'plans.manage',
  'promotions.read',
  'promotions.manage',
  'payments.read',
  'payments.detail.read',
  'payment_failures.manage',
  'billing_reconciliation.read',
  'billing_reconciliation.manage',
  'ai.overview.read',
  'ai.providers.read',
  'ai.providers.manage',
  'ai.models.read',
  'ai.models.manage',
  'ai.prompts.read',
  'ai.prompts.manage',
  'ai.usage.read',
  'ai.failures.manage',
  'ai.reports.manage',
  'ai.safety.read',
  'ai.safety.manage',
  'support.overview.read',
  'support.tickets.read',
  'support.tickets.manage',
  'support.tickets.detail.read',
  'support.tickets.assign',
  'support.tickets.priority',
  'support.tickets.reply',
  'support.tickets.notes',
  'support.tickets.resolve',
  'support.categories.read',
  'support.categories.manage',
  'feedback.read',
  'feedback.manage',
  'feedback.abuse.manage',
  'feedback.overview.read',
  'feedback.items.read',
  'feedback.items.detail.read',
  'feedback.items.link',
  'feedback.items.manage',
  'abuse.overview.read',
  'abuse.reports.read',
  'abuse.reports.detail.read',
  'abuse.reports.manage',
  'content.categories.read',
  'content.categories.manage',
  'content.manage',
  'content.tips.read',
  'content.tips.manage',
  'content.faqs.read',
  'content.faqs.manage',
  'content.onboarding.read',
  'content.onboarding.manage',
  'content.help_center.read',
  'content.help_center.manage',
  'content.announcements.read',
  'content.announcements.manage',
  'communications.templates.manage',
  'templates.email.read',
  'templates.email.manage',
  'templates.push.read',
  'templates.push.manage',
  'templates.transactional.read',
  'notifications.read',
  'notifications.overview.read',
  'notifications.campaigns.read',
  'notifications.campaigns.detail.read',
  'notifications.campaigns.manage',
  'notifications.audience.preview',
  'notifications.delivery.read',
  'security.events.read',
  'security.incidents.manage',
  'security.admins.read',
  'security.permissions.read',
  'security.support_access.read',
  'security.support_access.revoke',
  'audit.logs.read',
  'data_requests.exports.read',
  'data_requests.exports.manage',
  'data_requests.deletions.read',
  'data_requests.deletions.manage',
  'data_retention.read',
  'data_retention.manage',
] as const);

export const SYSTEM_ROLES = Object.freeze([
  'super-admin',
  'support-agent',
  'billing-operator',
  'import-operator',
  'ai-operator',
  'content-manager',
  'security-administrator',
] as const);
export type SystemRole = (typeof SYSTEM_ROLES)[number];

export const CLIENT_PERMISSION_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  'roles.read': 'access.roles.read',
  'roles.manage': 'access.roles.write',
  'admin-team.invite': 'access.invites.write',
  'admin-team.roles.assign': 'access.assignments.write',
  'support.request_access': 'support.access.request',
  'audit.logs.read': 'audit.read',
  'data_requests.exports.read': 'privacy.exports.read',
  'data_requests.exports.manage': 'privacy.exports.manage',
  'data_requests.deletions.read': 'privacy.deletions.read',
  'data_requests.deletions.manage': 'privacy.deletions.manage',
  'data_retention.read': 'retention.read',
  'data_retention.manage': 'retention.write',
});

const phase2Full = [
  'users.read',
  'devices.read',
  'sessions.read',
  'users.status.manage',
  'users.verification.manage',
  'devices.revoke',
  'sessions.revoke',
  'users.export_summary',
  'support.request_access',
  'support.access.read',
  'support.access.approve',
  'support.access.revoke',
  'support.access.use',
] as const;
const phase2Support = phase2Full.filter(
  (key) => !['devices.revoke', 'support.access.approve'].includes(key),
);
const phase4 = [
  'imports.read',
  'imports.detail.read',
  'imports.failures.manage',
  'imports.confidence.manage',
  'imports.duplicates.manage',
  'imports.unsupported.manage',
  'parsers.coverage.read',
  'parsers.senders.manage',
  'parsers.rules.read',
  'parsers.rules.manage',
  'parsers.tests.run',
  'parsers.versions.manage',
  'parsers.merchants.manage',
  'parsers.categories.manage',
] as const;
const phase5 = [
  'ai.overview.read',
  'ai.providers.read',
  'ai.providers.manage',
  'ai.models.read',
  'ai.models.manage',
  'ai.prompts.read',
  'ai.prompts.manage',
  'ai.usage.read',
  'ai.failures.manage',
  'ai.reports.manage',
  'ai.safety.read',
  'ai.safety.manage',
] as const;
const supportTickets = [
  'support.tickets.read',
  'support.tickets.manage',
  'support.tickets.detail.read',
  'support.tickets.assign',
  'support.tickets.priority',
  'support.tickets.reply',
  'support.tickets.notes',
  'support.tickets.resolve',
  'support.categories.read',
  'support.categories.manage',
] as const;
const feedback = [
  'feedback.read',
  'feedback.manage',
  'feedback.overview.read',
  'feedback.items.read',
  'feedback.items.detail.read',
  'feedback.items.link',
  'feedback.items.manage',
] as const;
const abuse = [
  'feedback.abuse.manage',
  'abuse.overview.read',
  'abuse.reports.read',
  'abuse.reports.detail.read',
  'abuse.reports.manage',
] as const;
const content = [
  'content.categories.read',
  'content.categories.manage',
  'content.manage',
  'content.tips.read',
  'content.tips.manage',
  'content.faqs.read',
  'content.faqs.manage',
  'content.onboarding.read',
  'content.onboarding.manage',
  'content.help_center.read',
  'content.help_center.manage',
  'content.announcements.read',
  'content.announcements.manage',
] as const;
const templates = [
  'communications.templates.manage',
  'templates.email.read',
  'templates.email.manage',
  'templates.push.read',
  'templates.push.manage',
  'templates.transactional.read',
] as const;
const notifications = [
  'notifications.read',
  'notifications.overview.read',
  'notifications.campaigns.read',
  'notifications.campaigns.detail.read',
  'notifications.campaigns.manage',
  'notifications.audience.preview',
  'notifications.delivery.read',
] as const;
const phase7 = [
  'security.events.read',
  'security.incidents.manage',
  'security.admins.read',
  'security.permissions.read',
  'security.support_access.read',
  'security.support_access.revoke',
  'audit.logs.read',
  'data_requests.exports.read',
  'data_requests.exports.manage',
  'data_requests.deletions.read',
  'data_requests.deletions.manage',
  'data_retention.read',
  'data_retention.manage',
] as const;
const phase8Read = [
  'system-health.api.read',
  'system-health.database.read',
  'system-health.storage.read',
  'system-health.providers.read',
  'jobs.queues.read',
  'jobs.runs.read',
  'jobs.schedules.read',
] as const;
const phase8Retry = [
  'system-health.providers.read',
  'jobs.queues.read',
  'jobs.runs.read',
  'jobs.runs.retry',
  'jobs.schedules.read',
] as const;
const backendOnlyPermissions = ['reference.read', 'reference.write'] as const;
const rawRolePermissions: Record<SystemRole, readonly string[]> = {
  'super-admin': [...CLIENT_PERMISSION_KEYS, ...backendOnlyPermissions],
  'support-agent': [
    'admin.overview.read',
    'global-search.use',
    'attention.read',
    ...phase2Support,
    'imports.read',
    'ai.overview.read',
    'ai.providers.read',
    'ai.failures.manage',
    'ai.reports.manage',
    ...supportTickets,
    ...feedback,
    'notifications.delivery.read',
  ],
  'billing-operator': [
    'admin.overview.read',
    'global-search.use',
    'attention.read',
    'subscriptions.read',
    'subscriptions.detail.read',
    'subscriptions.manage',
    'plans.read',
    'plans.manage',
    'promotions.read',
    'promotions.manage',
    'payments.read',
    'payments.detail.read',
    'payment_failures.manage',
    'billing_reconciliation.read',
    'billing_reconciliation.manage',
    'ai.overview.read',
    'ai.providers.read',
    'ai.models.read',
    'ai.usage.read',
    ...phase8Retry,
  ],
  'import-operator': [
    'admin.overview.read',
    ...phase4,
    'global-search.use',
    'attention.read',
    ...phase8Retry,
    'jobs.runs.cancel',
  ],
  'ai-operator': [
    'admin.overview.read',
    'global-search.use',
    'attention.read',
    ...phase5,
    ...phase8Retry,
    'jobs.runs.cancel',
  ],
  'content-manager': [
    'admin.overview.read',
    'global-search.use',
    'attention.read',
    ...content,
    ...templates,
    ...notifications,
    'feedback.read',
    'feedback.overview.read',
    'support.overview.read',
    ...phase8Retry,
    'jobs.runs.cancel',
  ],
  'security-administrator': [
    'admin.overview.read',
    'system-health.read',
    'global-search.use',
    'attention.read',
    ...phase2Full,
    'payments.read',
    'billing_reconciliation.read',
    'imports.read',
    'parsers.coverage.read',
    'parsers.rules.read',
    'ai.overview.read',
    'ai.providers.read',
    'ai.failures.manage',
    'ai.reports.manage',
    'ai.safety.read',
    ...abuse,
    'support.overview.read',
    ...phase7,
    ...phase8Read,
    'admin-team.read',
    'roles.read',
    'permissions.read',
    'settings.security.read',
    'settings.security.manage',
    'settings.maintenance.read',
    'reference.read',
  ],
};

const canonical = (key: string): string => CLIENT_PERMISSION_ALIASES[key] ?? key;
export const PERMISSION_KEYS = Object.freeze(
  [...new Set([...CLIENT_PERMISSION_KEYS.map(canonical), ...backendOnlyPermissions])].sort(),
);
export const SYSTEM_ROLE_PERMISSIONS = Object.freeze(
  Object.fromEntries(
    SYSTEM_ROLES.map((role) => [
      role,
      Object.freeze([...new Set(rawRolePermissions[role].map(canonical))].sort()),
    ]),
  ),
) as Readonly<Record<SystemRole, readonly string[]>>;

export const permissionManifestHash = createHash('sha256')
  .update(
    JSON.stringify({
      clientKeys: CLIENT_PERMISSION_KEYS,
      aliases: Object.entries(CLIENT_PERMISSION_ALIASES).sort(([left], [right]) =>
        left.localeCompare(right),
      ),
      roles: SYSTEM_ROLE_PERMISSIONS,
    }),
  )
  .digest('hex');
